/* config-kmplayer.h. Generated by cmake from config-kmplayer.h.cmake */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* have CAIRO */
#cmakedefine KMPLAYER_WITH_CAIRO 1

/* have GDBUS */
#cmakedefine KMPLAYER_WITH_GDBUS 1

/* have NPP */
#cmakedefine KMPLAYER_WITH_NPP 1
