/* config-kmplayer.h. Generated by cmake from config-kmplayer.h.cmake */

/* have CAIRO */
#cmakedefine KMPLAYER_WITH_CAIRO 1

/* have GDBUS */
#cmakedefine KMPLAYER_WITH_GDBUS 1

/* have NPP */
#cmakedefine KMPLAYER_WITH_NPP 1

/* use expat */
#cmakedefine KMPLAYER_WITH_EXPAT 1
