/* config.h. Generated by cmake from config.h.cmake */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* have CAIRO */
#cmakedefine HAVE_CAIRO 1

/* have GDBUS */
#cmakedefine HAVE_GDBUS 1

/* have NPP */
#cmakedefine HAVE_NPP 1
